name: Auto Fill PR Template

on:
    pull_request:
        types: [opened]

jobs:
    fill-pr-template:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Fill PR Template
              uses: repo-sync/pull-request@v2
              with:
                  github_token: ${{ secrets.CODESANDBOX_GITHUB_TOKEN }}
                  pr_title: 'Auto-filled PR Template'
                  pr_template: '.github/pull_request_template.md'
